# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'testJSPatchView' do
    platform :ios, '7.0'
    pod 'CocoaLumberjack'
end

target 'testJSPatchViewTests' do

end

target 'testJSPatchViewUITests' do

end

